### ISSUE TITLE
New Akvo API Plugin

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites#117]
Kominsky have been asked to create a Json plugin which would be a generic plugin utilising templates to make it more flexible.

As per below details/wireframes from @eefsparreboom :+1: 

"I have drawn a mockup of the functionalities for the API plugin. You can view it here:

http://app.mockflow.com/view/466493025A5E729947CAA1E00C0C9A5E

I have discussed them with Gabriel this morning and made some additional changes per his request. As you can see, on the right side there are four pages which you can click through. I will describe the functionalities per page below. First I want to explain the general scope of this idea. I am sorry if this is a long story, I tried to keep it as short as possible:

In his specifications, Gabriel had the idea to create plugins per JSON feed. For Wordpress, this is not an option, because each new plugin has to be submitted to the plugin library, which will get reviewed, then the developer gets access to a unique subversion repository where they have to commit their files to. In short, this will not work if you have to do this for every small feed you wish to implement to your site. It would be easier to let the developer dive into the code of your site.

So I have thought about this and decided to come up with a solution where there is only one plugin to be installed that enables different types of users to work with JSON feeds.
admin user: admin users have the right to edit the code of the website via the WP admin. I want to enable users with admin rights to create/edit JSON feed templates on their website. These are users with more in-depth knowledge of PHP and JSON.
editor / contributor users: these are the end users who will use the feed templates in their submitted content (eg. a page or a post)

Page 1: admin
This page will only be visible to admin users in the WP admin environment. When adding a new feed, only the first three fields will be visible:

Feed name: this identifies the feed. In this example, I have called it "Akvo updates", but this can be anything
JSON feed URL: In this field, the admin user enters the URL to be used to get the data. He can add the variables as they are (?project=42&limit=2&api_key=asdf1234qwer5678) or leave them empty(?project=&limit=&api_key=).
Update Interval: how often does the data need to be refreshed? 
When these first values are saved, the submitted form will be validated. A unique slug will be created to identify the feed (eg. "akvo_updates"), and the submitted feed URL will be disected for variables, which will appear in the default values section. In the default values section, the admin user can set the values he thinks an end user might not know or need to display the data. For this example, the api_key might never change, where a project id or limit might be different for two pages.

The template markup and template stylesheet area's enable the admin user to display the feed data in a format that is preferred for the particular website. A few lines of example code are prefilled in to get them started.

As not everything speaks for itself, there needs to be room for explanation and guidance in this page, hence the "lorem ipsum" paragraphs in the mockup.

Page 2: Editor - edit post / page
Here you see the general Wordpress admin page to edit posts or pages, with which every common wordpress user is familliar. To add the feed data into their content, the editor / contributor users click a button in the texteditor toolbar (in this example the right top red icon), at which point an overlay opens. At first, only the "select data feed" field is visible. When they select a feed, eg. "Akvo updates", the feed specific variable fields will appear. For this example, they will enter the project id and the limit of updates they want to show. The api key field is prefilled-in because the admin user has set the default value in the feed settings.

On "save", the feed is added to the cronjob schedule (so only feeds that are actually used will be updated), and a shortcode will be added to the text editor, which is visible in Page 3: Editor - edit post / page - shortcode

Page 4: Editor - widgets
In addition to adding data to your pages and posts, users might prefer to add a widget to their sidebars. The same principle applies here as in the edit post / page screen. 
The user drags the widget to the preferred sidebar, and first selects the feed they want to display. Next, they fill in the correct variables.

Additional notes
The original plan was to create a plugin per feed so people do not need to reinvent the wheel for a particular feed. For example, a popular news feed might be used by a lot of wordpress websites, and it would be a waste if every admin user would need to create their own templates. A possible solution for this might be to create a plugin wiki, where feeds of other users are stored so people can look up feeds and reuse them on their sites."

**Comment by lauraroverts** [comment]
@Lynngre is this still an outstanding issue?

**Comment by lauraroverts** [comment]
@Lynngre is this still an outstanding issue?
