### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#177]
Since we have renamed 'partnersites' (Akvo Pages) and 'consortium sites' (Akvo Sites), we should get rid of the old names.
Can you change the name of this repository into Akvo Sites https://github.com/akvo/akvo-consortia

**Comment by lauraroverts** [comment]
@carlio Is it possible to rename this repository into Akvo Sites?

**Comment by carlio** [comment]
@lauraroverts Yep absolutely. I think it'll work fine just to rename it, but make sure to let @eefsparreboom know as she'll probably have to update some config on her side.

**Comment by carlio** [comment]
@lauraroverts Do you want me to rename the repository now or wait?

**Comment by lauraroverts** [comment]
You can rename it. We created the repository, so not sure what @eefsparreboom would have to do with it.

**Comment by carlio** [comment]
Done!
