### ISSUE TITLE
intranet 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#190]
I wanted to add dehaan@aidenvironment.org to the WASH Alliance intranet, but I can't. WP admin says the email address is already in use. However, I can't find the email address in the admin. 

This problem seems to repeat itself, cause we had that in the pas a few times as well.

**Comment by lauraroverts** [comment]
Is there any clarity about this issue yet?

**Comment by eefsparreboom** [comment]
The user is already existing in the admin sites network. You can view / add / edit / delete all network users by going to My sites > Network admin > Users
![image](https://cloud.githubusercontent.com/assets/273377/5807780/d95d628c-a026-11e4-8df8-c138eee65850.png)

So if you want to start fresh with a user, you can delete the user here and add them again from the dashboard of the site you want to add them to. 

To add an existing user to a site, go to the dashboard of the site, go to Users > add new and enter the email address in the top box:
![image](https://cloud.githubusercontent.com/assets/273377/5807815/42c25f98-a027-11e4-9f25-ff9c9e531dcb.png)

For intranet users, select role **intranetuser**

I have not added this user for now, can you try it out as a practice run :P ?

**Comment by lauraroverts** [comment]
Thanks! It works!
I first deleted the user and added the user to the dashboard again.
