### ISSUE TITLE
Video channel does not work

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#191]
At http://www.rain4food.net/video/ I can't see any videos anymore at the English site. The spanish and french do show the videos.

**Comment by eefsparreboom** [comment]
Fixed, the html structure for the water channel page at
http://www.thewaterchannel.tv/categories/773-water-harvesting has changed,
and because of that the script that searches for movies on the site was not
finding any.

**Comment by lauraroverts** [comment]
Ok, but now the fr en sp show something different.

**Comment by eefsparreboom** [comment]
Yes, you are right. Now they all show the water channel!

**Comment by lauraroverts** [comment]
super
