### ISSUE TITLE
Add partner

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#193]
Hi Rumesh, 

I want to add a new partner Wilde Ganzen (http://www.wandelenvoorwater.nl/wp-admin/post.php?post=3480&action=edit) at the bottom of this page: http://www.wandelenvoorwater.nl/wat-we-doen/partners/

In the WordPress Admin I've added a post with the logo and text, I added Categorie 'Sponsors' and the Tag 'Ondersteund' like has been done with all the other partners that appear at that page. However, the post doesn't appear. Could it be that there is a maximum number of partners? I saw that http://www.wandelenvoorwater.nl/wp-admin/post.php?post=24&action=edit is also not visible at the Partner page. 

Do you know how I can add Wilde Ganzen to the page mentioned above? 
Thanks.

**Comment by rumeshkumar** [comment]
Hi Laura,

I will check on the issue and get back to you as soon as possible.

Thank you.

On 9 February 2015 at 18:14, lauraroverts <notifications@github.com> wrote:

> Hi Rumesh,
>
> I want to add a new partner Wilde Ganzen (
> http://www.wandelenvoorwater.nl/wp-admin/post.php?post=3480&action=edit)
> at the bottom of this page:
> http://www.wandelenvoorwater.nl/wat-we-doen/partners/
>
> In the WordPress Admin I've added a post with the logo and text, I added
> Categorie 'Sponsors' and the Tag 'Ondersteund' like has been done with all
> the other partners that appear at that page. However, the post doesn't
> appear. Could it be that there is a maximum number of partners? I saw that
> http://www.wandelenvoorwater.nl/wp-admin/post.php?post=24&action=edit is
> also not visible at the Partner page.
>
> Do you know how I can add Wilde Ganzen to the page mentioned above?
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/193>.
>



-- 

N Rumeshkumar
Webgurus International Pvt. Ltd.
4th floor, No: 58,
Darmapala Mawatha,
Colombo 7,
Sri Lanka.
website: www.webgurus.lk
TP: +94 117444741
Mobile: +94 771304626

**Comment by lauraroverts** [comment]
Can you give me an update on this issue?

**Comment by rumeshkumar** [comment]
It is fixed and committed the file to repo and uploaded to liver server.
You may check the page
<http://www.wandelenvoorwater.nl/wat-we-doen/partners/>.



On 17 February 2015 at 16:23, lauraroverts <notifications@github.com> wrote:

> Can you give me an update on this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/193#issuecomment-74649906>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 4th floor, No: 58, Darmapala
Mawatha, Colombo 7, Sri Lanka.
W: www.webgurus.lk | T: +94 117444741

**Comment by lauraroverts** [comment]
Perfect, thank you, it looks good!
