### ISSUE TITLE
Spam 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#194]
The last two weeks it looks like this website: http://www.washalliance.nl has got a lot of spam messages, posted as comments to posts. Sometimes I receive a natification in my email and then I can spam it, approve it, or trash it. 
Would it be possible to add a filter so that most spam automatically ends up in the spam folder?

**Comment by rumeshkumar** [comment]
Hi Laura,

I will check on your request and get back to you as soon as possible.

Thank you.

On 10 February 2015 at 12:28, lauraroverts <notifications@github.com> wrote:

> The last two weeks it looks like this website: http://www.washalliance.nl
> has got a lot of spam messages, posted as comments to posts. Sometimes I
> receive a natification in my email and then I can spam it, approve it, or
> trash it.
> Would it be possible to add a filter so that most spam automatically ends
> up in the spam folder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/194>.
>



-- 

N Rumeshkumar
Webgurus International Pvt. Ltd.
4th floor, No: 58,
Darmapala Mawatha,
Colombo 7,
Sri Lanka.
website: www.webgurus.lk
TP: +94 117444741
Mobile: +94 771304626

**Comment by rumeshkumar** [comment]
I have done some research on overcoming spam issues today and found that a
plugin called Akismet is a best one to use. This plugin is already
installed and configured. Akismet automatically checks all incoming
comments and filter them. If you want to let Akismet know something is
spam, please click here <http://docs.akismet.com/general/teach-akismet/> to
know how to do it.

Using CAPTCHA is not recommended for many reasons. But If you really want
to add CAPTCHA in comments form in addition to Akismet, I can do it. But I
think we can wait for few months and see how Akismet works.

On 10 February 2015 at 22:42, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
wrote:

> Hi Laura,
>
> I will check on your request and get back to you as soon as possible.
>
> Thank you.
>
> On 10 February 2015 at 12:28, lauraroverts <notifications@github.com>
> wrote:
>
>> The last two weeks it looks like this website: http://www.washalliance.nl
>> has got a lot of spam messages, posted as comments to posts. Sometimes I
>> receive a natification in my email and then I can spam it, approve it, or
>> trash it.
>> Would it be possible to add a filter so that most spam automatically ends
>> up in the spam folder?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/194>.
>>
>
>
>
> --
>
> N Rumeshkumar
> Webgurus International Pvt. Ltd.
> 4th floor, No: 58,
> Darmapala Mawatha,
> Colombo 7,
> Sri Lanka.
> website: www.webgurus.lk
> TP: +94 117444741
> Mobile: +94 771304626
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 4th floor, No: 58, Darmapala
Mawatha, Colombo 7, Sri Lanka.
W: www.webgurus.lk | T: +94 117444741

**Comment by lauraroverts** [comment]
Ok, fine with me. Let's used the Akismet plugin.
