### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#196]
At http://www.rain4food.net/community/ halfway the page there is an error message: "An invalid security key was specified. Please use at least the following shortcode: [advanced_iframe securitykey="<your security key - see settings>"]. Please also check in the html mode that your shortcode does only contain notmal spaces and not a &nbsp; instead." 

Not sure what this means.

**Comment by rumeshkumar** [comment]
Hi Laura,

I have done some fixes. Please let me know whether the page is displaying properly or not.

**Comment by lauraroverts** [comment]
I asked the partner. Will let you know as soon as the partner replies.

**Comment by lauraroverts** [comment]
haven't heard from the partner, so I assume it looks good like this. Thanks!  I'll close the issue.
