### ISSUE TITLE
Project update duplication - http://connect4change.nl/

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites#197]
Seeing 19 Feb Project update duplication http://connect4change.nl/
![screen shot 2015-03-23 at 11 11 54](https://cloud.githubusercontent.com/assets/2675262/6777827/9c6dc4a4-d14d-11e4-9d83-d3715568e0c7.png)

**Comment by rumeshkumar** [comment]
Hi,

connect4change fetch projects update using Akvo RSR to display on the site. I can see that the above mentioned project has two updates in Akvoapp.org. that is the reason, there are two entries in connect4change. You may have a look at "Latest Project Updates" section by visiting the following link.

http://connect4change.akvoapp.org/project/352/

**Comment by lauraroverts** [comment]
Yes that's correct. Update is posted twice by partner: http://connect4change.akvoapp.org/project/352/update/8680/ and http://connect4change.akvoapp.org/project/352/update/8681/ I've deleted 8680 from the RSR admin so will be synced with the C4C website.
