### ISSUE TITLE
videos don't sync

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#198]
At http://www.wandelenvoorwater.nl/media/video/ the videos of the following YouTube channel are displayed: https://www.youtube.com/channel/UCzzt85MtSWR6jVOJnurMsaw

I thought the last uploaded video would automatically appear on top, but it seems that the video that was uploaded today (https://www.youtube.com/watch?v=P9eAnzWGPb0&list=PL6Tovc21nZM6XaS_lqcZM8isUtjE40QcC) doesn't appear there. 

Could you check when and how this is synced?

**Comment by rumeshkumar** [comment]
I will check on this and give you an update as soon as possible. (probably by Monday)

**Comment by rumeshkumar** [comment]
Dear Laura,

I can see that there are only 11 videos in "Wandelen vwater" YouTube channel and all these 11 videos are listed on wandelenvoorwater.nl. Video added last will appear first automatically. 

The video you said is uploaded to a different channel named "Karin van den Boogaert". 

Please check this and let me know if there are any more issues.

Thank you.

**Comment by lauraroverts** [comment]
Hi Rumesh, Now I understand. The video is just linked to the Wandelen vwater channel, but not uploaded there. I'll explain to the partner so that they can upload the video again to the appropriate channel. 
Thanks for your help.
