### ISSUE TITLE
YouTube plugin 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#203]
Hi Rumesh, 

Could you please check if the YouTube plugin that is integrated in many of the Akvo Sites is up to date? Just noticed that on http://www.washalliance.nl/learn-more/video/ and http://www.gnwp.nl/video/ and http://connect4change.nl/video/ and http://footballforwater.nl/video/ and http://www.walkingforwater.eu/media/videos/ (and perhaps some more! ) are not working correctly.

**Comment by rumeshkumar** [comment]
I will check them as soon as possible.

On 12 May 2015 at 17:03, lauraroverts <notifications@github.com> wrote:

> Assigned #203 <https://github.com/akvo/akvo-sites/issues/203> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#event-302710003>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
Due to the changes in YouTube API, the plugin we use supports only
"Playlists" now.

The following sites are displaying videos now

http://www.washalliance.nl/learn-more/video

http://connect4change.nl/video/  - There are more than one playlist so all
of them are displayed in the page. If you want specific one to display,
please let me know

http://www.walkingforwater.eu/media/videos/ - There are more then one
playlist so videos from one of them are displayed. Please let me know if
you want to display more playlist. Send playlist ID as well.

http://marsfarmersfirst.com/video/




Please send me playlist ID for the following sites

http://www.gnwp.nl/video/

http://footballforwater.nl/video/ - There are many videos but no playlist
created. Please create a playlist of all the videos and send me the
playlist ID

http://wump3r.net/video/


On 12 May 2015 at 17:08, Rumeshkumar Navaratnam <rumesh@webgurus.lk> wrote:

> I will check them as soon as possible.
>
> On 12 May 2015 at 17:03, lauraroverts <notifications@github.com> wrote:
>
>> Assigned #203 <https://github.com/akvo/akvo-sites/issues/203> to
>> @rumeshkumar <https://github.com/rumeshkumar>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/203#event-302710003>.
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
For Walking for Water, please use the same ID as for Wandelen voor Water: UUzzt85MtSWR6jVOJnurMsaw

The other ones I'll let you know. 

It is not possible anymore to just display all videos from a particular channel? For Connect4Change it would mean they want to display the videos from all playlists.

**Comment by rumeshkumar** [comment]
Changes in Walking for Water is done.

The plugin we use is not updated to work with the YouTube API changes by
the author. So, displaying all the videos from a channel is not possible.
The solution is to use playlist method for now. I will spend some time to
look for alternative plugin to use later.

So, if there are a new playlists created, admin has to just enter the
following in the text editor of video page. There can be multiple
playlists.

====================================================

[Playlist name 1]

[Youtube_Channel_Gallery feed="playlist" user="[playlist ID]"
feedorder="asc" videowidth="580" ratio="16x9" theme="dark" color="grey"
quality="small" autoplay="0" rel="1" showinfo="1" maxitems="20"
thumbwidth="180" thumbratio="16x9" thumbcolumns="3" title="1"
description="1" thumbnail_alignment="center" descriptionwordsnumber="10"
link_window="0"]

[Playlist name 2]

[Youtube_Channel_Gallery feed="playlist" user="[playlist ID]"
feedorder="asc" videowidth="580" ratio="16x9" theme="dark" color="grey"
quality="small" autoplay="0" rel="1" showinfo="1" maxitems="20"
thumbwidth="180" thumbratio="16x9" thumbcolumns="3" title="1"
description="1" thumbnail_alignment="center" descriptionwordsnumber="10"
link_window="0"]

.......

======================================================


On 19 May 2015 at 18:13, lauraroverts <notifications@github.com> wrote:

> For Walking for Water, please use the same ID as for Wandelen voor Water:
> UUzzt85MtSWR6jVOJnurMsaw
>
> The other ones I'll let you know.
>
> It is not possible anymore to just display all videos from a particular
> channel? For Connect4Change it would mean they want to display the videos
> from all playlists.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-103472392>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
I can see that the video at http://www.walkingforwater.eu is working again. However, at the homepage it still gives an error. And there is one box missing underneath the video box.

**Comment by rumeshkumar** [comment]
Sorry, I forgot to about it. The homepage video issue is fixed now. QA team
is testing all the sites page by page to check YouTube videos. If they
report any issues, I will fix them as well.

On 20 May 2015 at 20:16, lauraroverts <notifications@github.com> wrote:

> I can see that the video at http://www.walkingforwater.eu is working
> again. However, at the homepage it still gives an error. And there is one
> box missing underneath the video box.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-103912124>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Thanks Rumesh. 

Hereby the GNWP Playlist ID: https://www.youtube.com/watch?v=M6cxiONBXr4&list=UU9bKtqBXpsl4E449bR1XADA

**Comment by rumeshkumar** [comment]
Tha following sites are fine now

http://washalliance.nl
http://connect4change.nl
http://srhralliance.org
http://walkingforwater.eu
http://marsfarmersfirst.com
http://wash-liberia.org
http://rain4food.net
http://wandelenvoorwater.nl
http://gnwp.nl


and I am waiting for Playlist ID of the following sites

http://footballforwater.nl
http://wump3r.net


I am very busy with other projects currently but I will spend some time to
look for better solution for this YouTube video issue and update you
regarding it.


On 21 May 2015 at 17:10, lauraroverts <notifications@github.com> wrote:

> Thanks Rumesh.
>
> Hereby the GNWP Playlist ID:
> https://www.youtube.com/watch?v=M6cxiONBXr4&list=UU9bKtqBXpsl4E449bR1XADA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-104237338>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
GNWP website does not need to be changed. We expect the website to be offline soon. 
Football for Water I'm still waiting for the Playlist ID. 

I just noticed (on http://www.gnwp.nl and http://www.wandelenvoorwater.nl) that the date at the video is at Jan 01 1970, see screenshots. Please check for all websites. 
![screen shot 2015-05-28 at 08 50 13](https://cloud.githubusercontent.com/assets/4179989/7854125/9fa7c1a4-0516-11e5-8257-22164c25c7be.png)

**Comment by rumeshkumar** [comment]
The date issue in video fixed.

On 28 May 2015 at 12:20, lauraroverts <notifications@github.com> wrote:

> GNWP website does not need to be changed. We expect the website to be
> offline soon.
> Football for Water I'm still waiting for the Playlist ID.
>
> I just noticed (on http://www.gnwp.nl and http://www.wandelenvoorwater.nl)
> that the date at the video is at Jan 01 1970, see screenshots. Please check
> for all websites.
> [image: screen shot 2015-05-28 at 08 50 13]
> <https://cloud.githubusercontent.com/assets/4179989/7854125/9fa7c1a4-0516-11e5-8257-22164c25c7be.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-106198655>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
GNWP website will be taken offline probably soon. Therefore there won't be a playlist ID. 

I'm still waiting for the Football for Water playlist ID.

**Comment by lauraroverts** [comment]
At GNWP homepage, the video box has disappeared again and shows a date Jan 01 1970: http://www.gnwp.nl

Also at http://www.washalliance.nl/learn-more/video/ I don't see the videos anymore.

**Comment by rumeshkumar** [comment]
The 3rd party plugin we use to display YouTube video is broken I think. I
have spent some time and found a reasonable alternative plugin. Here, admin
has to enter YouTube or vimeo link and then can give title, description. I
will check this plugin and give you an update by Monday.
You also may have a look at the plugin.

https://wordpress.org/plugins/gallery-video/

On 4 June 2015 at 17:08, lauraroverts <notifications@github.com> wrote:

> At GNWP homepage, the video box has disappeared again and shows a date Jan
> 01 1970: http://www.gnwp.nl
>
> Also at http://www.washalliance.nl/learn-more/video/ I don't see the
> videos anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-108853880>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
The 3rd plugin we used is upgraded as per its authors. I will work on this
tomorrow and fix the issue in all the sites. If it still give problems, I
will use another plugin. This issue is taking more time.

On 4 June 2015 at 18:02, Rumeshkumar Navaratnam <rumesh@webgurus.lk> wrote:

> The 3rd party plugin we use to display YouTube video is broken I think. I
> have spent some time and found a reasonable alternative plugin. Here, admin
> has to enter YouTube or vimeo link and then can give title, description. I
> will check this plugin and give you an update by Monday.
> You also may have a look at the plugin.
>
> https://wordpress.org/plugins/gallery-video/
>
> On 4 June 2015 at 17:08, lauraroverts <notifications@github.com> wrote:
>
>> At GNWP homepage, the video box has disappeared again and shows a date
>> Jan 01 1970: http://www.gnwp.nl
>>
>> Also at http://www.washalliance.nl/learn-more/video/ I don't see the
>> videos anymore.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-108853880>.
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
Dear Laura,

I worked on YouTube video issue today. Video pages in most of the sites are
working fine now. But there are issues in Home page still and I am working
on it.

Please give "user" parameter value of the following sites:

http://walkingforwater.eu
http://wandelenvoorwater.nl
http://gnwp.nl


You can find the user parameter value by logging into the YouTube account
which you use to upload videos. When you go to a YouTube channel, you will
see the URL in a format as follows

www.youtube.com/user/MarsSustainability



*Summary of wrok done*

http://washalliance.nl - WASHAlliance


Home - No videos

Video page - working



http://connect4change.nl - c4cconsortium

Home - No videos

Video page - Working

http://srhralliance.org

Home - No videos

Video page - No page

http://walkingforwater.eu - ??

Home - Have to fix

Video page - I could not find a value for user. So "Wandelen voor Water
2015" playlist is displayed currently. An example user value is as below.


www.youtube.com/user/MarsSustainability


http://marsfarmersfirst.com - MarsSustainability

Home -  Have to fix

Video page - Working


http://wash-liberia.org

Home - No videos

Video page - No page


http://rain4food.net

Home - No videos

Video page - No YouTube videos


http://wandelenvoorwater.nl - ??

Home - Have to fix

Video page - I could not find a value for user. So "Wandelen voor Water
2015" playlist is displayed currently. An example user value is as below.


www.youtube.com/user/MarsSustainability



http://gnwp.nl - ??

Home - Have to fix

Video page - I could not find a value for user. So "AKVO" playlist is
displayed currently.

http://footballforwater.nl - foorballforwater

Home - Have to fix

Video page - Working


http://wump3r.net - RAINfoundation

Home - Have to fix

Video page - Working


On 11 June 2015 at 10:55, Rumeshkumar Navaratnam <rumesh@webgurus.lk> wrote:

> The 3rd plugin we used is upgraded as per its authors. I will work on this
> tomorrow and fix the issue in all the sites. If it still give problems, I
> will use another plugin. This issue is taking more time.
>
> On 4 June 2015 at 18:02, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
> wrote:
>
>> The 3rd party plugin we use to display YouTube video is broken I think. I
>> have spent some time and found a reasonable alternative plugin. Here, admin
>> has to enter YouTube or vimeo link and then can give title, description. I
>> will check this plugin and give you an update by Monday.
>> You also may have a look at the plugin.
>>
>> https://wordpress.org/plugins/gallery-video/
>>
>> On 4 June 2015 at 17:08, lauraroverts <notifications@github.com> wrote:
>>
>>> At GNWP homepage, the video box has disappeared again and shows a date
>>> Jan 01 1970: http://www.gnwp.nl
>>>
>>> Also at http://www.washalliance.nl/learn-more/video/ I don't see the
>>> videos anymore.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-108853880>.
>>>
>>
>>
>>
>> --
>> Regards,
>> N Rumeshkumar
>>
>> *Project Manager*
>> M: +94 771304626 | Skype: rumeshin
>>
>> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road,
>> Rajagiriya, Sri Lanka.
>> W: www.webgurus.lk | T: +94 114502542
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
Dear Laura,

I worked on YouTube video issue (Home page) today.

*Please send me  "user" parameter value of the following sites:*

*http://walkingforwater.eu* <http://walkingforwater.eu/>
*http://wandelenvoorwater.nl* <http://wandelenvoorwater.nl/>
*http://gnwp.nl* <http://gnwp.nl/>


You can find the user parameter value by logging into the YouTube account
which you use to upload videos. When you go to a YouTube channel, you will
see the URL in a format as follows

www.youtube.com/user/MarsSustainability



*Summary of wrok done*

http://washalliance.nl - WASHAlliance


Home - No videos

Video page - working



http://connect4change.nl - c4cconsortium

Home - No videos

Video page - Working

http://srhralliance.org

Home - No videos

Video page - No page

http://walkingforwater.eu - ??

Home - Have to fix

Video page - I could not find a value for user. So "Wandelen voor Water
2015" playlist is displayed currently. An example user value is as below.


www.youtube.com/user/MarsSustainability


http://marsfarmersfirst.com - MarsSustainability

Home -  Working

Video page - Working


http://wash-liberia.org

Home - No videos

Video page - No page


http://rain4food.net

Home - No videos

Video page - No YouTube videos


http://wandelenvoorwater.nl - ??

Home - Have to fix

Video page - I could not find a value for user. So "Wandelen voor Water
2015" playlist is displayed currently. An example user value is as below.


www.youtube.com/user/MarsSustainability



http://gnwp.nl - ??

Home - Have to fix

Video page - I could not find a value for user. So "AKVO" playlist is
displayed currently.

http://footballforwater.nl - foorballforwater

Home - Working

Video page - Working


http://wump3r.net - RAINfoundation


Home - Working

Video page - Working


On 12 June 2015 at 17:59, Rumeshkumar Navaratnam <rumesh@webgurus.lk> wrote:

> Dear Laura,
>
> I worked on YouTube video issue today. Video pages in most of the sites
> are working fine now. But there are issues in Home page still and I am
> working on it.
>
> Please give "user" parameter value of the following sites:
>
> http://walkingforwater.eu
> http://wandelenvoorwater.nl
> http://gnwp.nl
>
>
> You can find the user parameter value by logging into the YouTube account
> which you use to upload videos. When you go to a YouTube channel, you will
> see the URL in a format as follows
>
> www.youtube.com/user/MarsSustainability
>
>
>
> *Summary of wrok done*
>
> http://washalliance.nl - WASHAlliance
>
>
> Home - No videos
>
> Video page - working
>
>
>
> http://connect4change.nl - c4cconsortium
>
> Home - No videos
>
> Video page - Working
>
> http://srhralliance.org
>
> Home - No videos
>
> Video page - No page
>
> http://walkingforwater.eu - ??
>
> Home - Have to fix
>
> Video page - I could not find a value for user. So "Wandelen voor Water
> 2015" playlist is displayed currently. An example user value is as below.
>
>
> www.youtube.com/user/MarsSustainability
>
>
> http://marsfarmersfirst.com - MarsSustainability
>
> Home -  Have to fix
>
> Video page - Working
>
>
> http://wash-liberia.org
>
> Home - No videos
>
> Video page - No page
>
>
> http://rain4food.net
>
> Home - No videos
>
> Video page - No YouTube videos
>
>
> http://wandelenvoorwater.nl - ??
>
> Home - Have to fix
>
> Video page - I could not find a value for user. So "Wandelen voor Water
> 2015" playlist is displayed currently. An example user value is as below.
>
>
> www.youtube.com/user/MarsSustainability
>
>
>
> http://gnwp.nl - ??
>
> Home - Have to fix
>
> Video page - I could not find a value for user. So "AKVO" playlist is
> displayed currently.
>
> http://footballforwater.nl - foorballforwater
>
> Home - Have to fix
>
> Video page - Working
>
>
> http://wump3r.net - RAINfoundation
>
> Home - Have to fix
>
> Video page - Working
>
>
> On 11 June 2015 at 10:55, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
> wrote:
>
>> The 3rd plugin we used is upgraded as per its authors. I will work on
>> this tomorrow and fix the issue in all the sites. If it still give
>> problems, I will use another plugin. This issue is taking more time.
>>
>> On 4 June 2015 at 18:02, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
>> wrote:
>>
>>> The 3rd party plugin we use to display YouTube video is broken I think.
>>> I have spent some time and found a reasonable alternative plugin. Here,
>>> admin has to enter YouTube or vimeo link and then can give title,
>>> description. I will check this plugin and give you an update by Monday.
>>> You also may have a look at the plugin.
>>>
>>> https://wordpress.org/plugins/gallery-video/
>>>
>>> On 4 June 2015 at 17:08, lauraroverts <notifications@github.com> wrote:
>>>
>>>> At GNWP homepage, the video box has disappeared again and shows a date
>>>> Jan 01 1970: http://www.gnwp.nl
>>>>
>>>> Also at http://www.washalliance.nl/learn-more/video/ I don't see the
>>>> videos anymore.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-108853880>.
>>>>
>>>
>>>
>>>
>>> --
>>> Regards,
>>> N Rumeshkumar
>>>
>>> *Project Manager*
>>> M: +94 771304626 | Skype: rumeshin
>>>
>>> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road,
>>> Rajagiriya, Sri Lanka.
>>> W: www.webgurus.lk | T: +94 114502542
>>>
>>
>>
>>
>> --
>> Regards,
>> N Rumeshkumar
>>
>> *Project Manager*
>> M: +94 771304626 | Skype: rumeshin
>>
>> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road,
>> Rajagiriya, Sri Lanka.
>> W: www.webgurus.lk | T: +94 114502542
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Hi Rumesh, I don't exactly understand the problem. 

This is the link to the GNWP playlist ID: https://www.youtube.com/watch?v=M6cxiONBXr4&list=UU9bKtqBXpsl4E449bR1XADA From here I think you can see that the user is WitteveenBos Ghana, right? 
![screen shot 2015-06-15 at 11 33 19](https://cloud.githubusercontent.com/assets/4179989/8157125/6706ea88-1352-11e5-9b8a-a8487fe157ea.png)

Walking for Water and Wandelen voor Water use the same YouTube channel: playlist ID UUzzt85MtSWR6jVOJnurMsaw

**Comment by rumeshkumar** [comment]
The one displayed is channel name. Most of the time channel name and "user"
values are same. but in the case of walkingforwater.eu, wandelenvoorwater.nl
and gnwp.nl, both are different.

For ex, if you go to https://www.youtube.com/user/rumesh272004, the user
value is *rumesh272004, *but under the videos it displays *rumeshkumar
navaratnam. *

I hope you get the difference.

On 15 June 2015 at 15:07, lauraroverts <notifications@github.com> wrote:

> Hi Rumesh, I don't exactly understand the problem.
>
> This is the link to the GNWP playlist ID:
> https://www.youtube.com/watch?v=M6cxiONBXr4&list=UU9bKtqBXpsl4E449bR1XADA
> From here I think you can see that the user is WitteveenBos Ghana, right?
> [image: screen shot 2015-06-15 at 11 33 19]
> <https://cloud.githubusercontent.com/assets/4179989/8157125/6706ea88-1352-11e5-9b8a-a8487fe157ea.png>
>
> Walking for Water and Wandelen voor Water use the same YouTube channel:
> playlist ID UUzzt85MtSWR6jVOJnurMsaw
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-111997622>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
So for GNWP the username is WitteveenBos Ghana
For Wandelen voor Water / Walking for water: wandelenvwater

**Comment by rumeshkumar** [comment]
I will skype with you today.

On 15 June 2015 at 16:41, lauraroverts <notifications@github.com> wrote:

> So for GNWP the username is WitteveenBos Ghana
> For Wandelen voor Water / Walking for water: wandelenvwater
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-112020207>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
YouTube videos are working fine in all the sites now. Please have a look
and let me know your feedback.

On 16 June 2015 at 10:51, Rumeshkumar Navaratnam <rumesh@webgurus.lk> wrote:

> I will skype with you today.
>
> On 15 June 2015 at 16:41, lauraroverts <notifications@github.com> wrote:
>
>> So for GNWP the username is WitteveenBos Ghana
>> For Wandelen voor Water / Walking for water: wandelenvwater
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/203#issuecomment-112020207>.
>>
>
>
>
> --
> Regards,
> N Rumeshkumar
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542
