### ISSUE TITLE
RAIN4Food testimonial box and documents page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#205]
Hi Rumesh, pasting this issue in Github (instead of email)  to keep the overview: 

For RAIN4Food website there are two requirements:
- Testimonial slider: set sliding time to approx 8 seconds
- Download page: can be built according to the mockup you created. The ambassador page will stay the same as it looks now.

**Comment by rumeshkumar** [comment]
It is done. Please check the email I sent you and give your feedback.

**Comment by lauraroverts** [comment]
Dear Laura,

I have done the following for Rain4Food website:

- Changed slider delay to 8000 millisecond

- The download page is created and published privately. I will make it public and add a menu item under Knowledge once you finish adding content to the page.

The page uses some shotcodes for layout. 

you can see the following shortcodes in the page

[row]
[column lg="4" md="4" sm="4" xs="12" ] 

Content for 1st column (English)

[/column]
[column lg="4" md="4" sm="4" xs="12" ]

Content for 2nd column (Spanish)

[/column]
[column lg="4" md="4" sm="4" xs="12" ]

Content for 3rd column (French)

[/column]
[/row]

I have added some samples. You can follow that to add new once. You can use "
<hr />" to display dotted lines under each item as shown in the page.

If this is unclear. please let me know. I can explain you on Skype.

**Comment by lauraroverts** [comment]
Dear Rumesh, I've checked with the organisation. The downloads page can be published now.

**Comment by rumeshkumar** [comment]
The download page is published now.

On 11 June 2015 at 14:34, lauraroverts <notifications@github.com> wrote:

> Dear Rumesh, I've checked with the organisation. The downloads page can be
> published now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/205#issuecomment-111051711>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
thank you.
