### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#208]
Trying to add a logo to http://srhralliance.org/who-we-are/alliance-members/ Rutgers. However, in the WP admin the add/edit logo button has disappeared. It is now not possible to add a new logo. 
![screen shot 2015-06-29 at 09 06 27](https://cloud.githubusercontent.com/assets/4179989/8402785/bdfa32c2-1e3e-11e5-822e-e22c7aa2d540.png)

**Comment by rumeshkumar** [comment]
I can see the upload link both in "Add new" and "Edit" pages. Please make
sure that "alliance members" category is selected. Mouse over the box
displayed under "logo" label to edit the image in "Edit" page.

Please recheck.

On 29 June 2015 at 12:41, lauraroverts <notifications@github.com> wrote:

> Assigned #208 <https://github.com/akvo/akvo-sites/issues/208> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/208#event-342657923>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
I managed to add the logo, but now the footer is messed up. 
![screen shot 2015-06-29 at 11 28 57](https://cloud.githubusercontent.com/assets/4179989/8405052/155a5d04-1e52-11e5-9a91-6a98c3cce08b.png)

**Comment by rumeshkumar** [comment]
fixed it. Please check and give your feedback.

On 29 June 2015 at 14:59, lauraroverts <notifications@github.com> wrote:

> I managed to add the logo, but now the footer is messed up.
> [image: screen shot 2015-06-29 at 11 28 57]
> <https://cloud.githubusercontent.com/assets/4179989/8405052/155a5d04-1e52-11e5-9a91-6a98c3cce08b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/208#issuecomment-116568076>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Only thing is that the Rutgers logo looks blurry
![image001](https://cloud.githubusercontent.com/assets/4179989/8407143/0b3a0006-1e64-11e5-94c1-7ce4d682f5cf.jpg)

**Comment by rumeshkumar** [comment]
I think it looks better now. Uploaded image should be in good quality.

On 29 June 2015 at 17:07, lauraroverts <notifications@github.com> wrote:

> Only thing is that the Rutgers logo looks blurry
> [image: image001]
> <https://cloud.githubusercontent.com/assets/4179989/8407143/0b3a0006-1e64-11e5-94c1-7ce4d682f5cf.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/208#issuecomment-116623119>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
thanks
