### ISSUE TITLE
Remove support points 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#209]
When a school registers on http://www.wandelenvoorwater.nl, there appears a list of support points (steunpunten) to choose from.  I can add new ones, but can’t delete old ones or ones that are redundant (in there twice).  The list is now getting too long, and really needs a clean up. Can you give me more rights so that I can delete support points? 
http://www.wandelenvoorwater.nl/wp-admin/admin.php?page=AWPR_supportpoints

See below a screenshot of what I see in the admin: 
![screen shot 2015-06-29 at 13 35 13](https://cloud.githubusercontent.com/assets/4179989/8407121/bb73a432-1e63-11e5-8334-21a640a1d0f9.png)

**Comment by rumeshkumar** [comment]
There are 69 support points added by default when activating the
Participant Registry plugin. I hope giving permission to delete support
points which are added by the admin is good. What do you think?

On 29 June 2015 at 17:05, lauraroverts <notifications@github.com> wrote:

> Assigned #209 <https://github.com/akvo/akvo-sites/issues/209> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/209#event-342901831>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Makes sense to me

**Comment by rumeshkumar** [comment]
I have finished this task today. I will deploy the changes to live tomorrow morning and send you a message

**Comment by rumeshkumar** [comment]
I have deployed the changes this morning and tested on production. 

- Go to Participant Registry => Supportpoints
- You will see "Remove" buttons in the 2nd column of  the table. This remove button is available only to the supportpoints an admin added
- Click on it and it will take you to the confirmation page. If there are any participants data which use this supportpoint, you will see a warning message saying the same. Please note that removing a supportpoint will also remove all participant data which use the supportpoint
- Once you click on remove, you will see a success message page.

Please have a look and let me know your feedback.

**Comment by lauraroverts** [comment]
The person who requested this is on holiday, so I haven't heard if this works fine. I assume it is okay. Otherwise I will let you know.
