### ISSUE TITLE
set cron jobs Akvo Sites

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#210]
In order to show the latest RSR project updates at the current Akvo Sites, built by Kominski, cron jobs need to be setup. 

According to @rumeshkumar , Kominski: 
I have tested the Akvo RSR (Projects, Project locations and Project updates) for a week now and it is working fine. So we can set cron job now. 

I have developed this as a temporary solution. I hope having the following features in Akvo API will help me to improve my code and make it more efficient.

- Feature to get project updates by organization ID and limit number of project updates per project 
   For ex: rsr.akvo.org/rest/v1/project_update/?partners=275&per_project=10
   This should be able to supply latest 10 project updates per project in organization 275

- If getting project update by organization ID is not possible, at-least I would like to get latest 10 project updates by project ID. I do not think storing all the project updates in every website is useful as those can be viewed in rsr.akvo.org.
 For ex: http://rsr.akvo.org/rest/v1/project_update/?project=475&limit=10

Please let me know if there are any updates on the about mentioned points. So that I can do modification to my code.

@orifito  please cancel existing cron jobs. Those are  

- /wp-content/plugins/akvo-partner-communication/CronController.php
- /wp-content/plugins/akvo-partner-communication/SyncController.php

and please set the following cron jobs. I had to make it per site to avoid Gateway Timeout issue. I think running this once a day in a off-peak time should be fine. Please give 5 minutes interval after each cron job. For ex, if GNWP runs at 10:00, Wash Alliance should start to run 10:05. 

Note: Please note that Rain 4 Food uses different URL.

Cron jobs

GNWP
http://gnwp.nl/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=2121

Wash Alliance
http://www.washalliance.nl/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=275

Connect 4 Change
http://connect4change.nl/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=272

Football for Water
http://footballforwater.nl/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=1060

MARS
marsfarmersfirst.com/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=539

SRHR Alliance
http://srhralliance.org/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=912

Wash Liberia
http://wash-liberia.org/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=1061

Wandelen voor water
http://www.wandelenvoorwater.nl/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=1151

Walking for water
http://www.walkingforwater.eu/wp-content/plugins/akvo-temp-display-map/CronController.php?id_organisation=2151

Rain for food
http://www.rain4food.net/wp-content/plugins/akvo-temp-display-map/CronControllerKeyword.php?keyword=rain4food

**Comment by orifito** [comment]
Changes applied :smiley: Set new cronjobs to run on a daily basis at 6am.
Please reopen this issue in case something is wrong.
