### ISSUE TITLE
add line of code in config file

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#212]
The following code has to be put in the Kominski Akvo Sites wp-config file as soon as possible as @rumeshkumar  does not have access permission to edit the file. This can be added at the end of the file. See screenshot

define( 'WP_AUTO_UPDATE_CORE', minor );

The file is located in "/var/akvo/akvosites/code/wp-config.php"
![screenshot](https://cloud.githubusercontent.com/assets/4179989/9056847/170ed7d2-3a96-11e5-8553-b97b80c1043a.jpg)

**Comment by orifito** [comment]
Applied to current test installation

**Comment by orifito** [comment]
@lauraroverts is this needed in new akvosites installation for Z&Z template? or it was only for Kominski akvo sites?

**Comment by lauraroverts** [comment]
As far as I know this applies to the Kominski sites only.

**Comment by rumeshkumar** [comment]
Yes, Only for Kominski sites (WordPress)

On 14 September 2015 at 17:40, lauraroverts <notifications@github.com>
wrote:

> As far as I know this applies to the Kominski sites only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/212#issuecomment-140050577>.
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by orifito** [comment]
@lauraroverts @rumeshkumar great, thanks!
