### ISSUE TITLE
Dropbox GNWP secure page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#213]
Via the dropbox at password secured page www.gnwp.nl/secure people can access documents in the dropbox. 

However, the login details are connected to one of the WP-admins for this website Kim Geleynse and thus give access to the Admin page. This give other people the opportunity to make changes to the website. Would it be possible to: 

-Disconnect the login details from Kim's details? 
-Disconnect the login details from the WP Admin? 
 
If so, I can give you the login details the dropbox needs to be connected to.

**Comment by rumeshkumar** [comment]
I have created an account with username "gnwp" and password "gnwp20142020".
This user is a subscriber.

I think GNWP shared Kim's username and password with other people to give
access the dropbox files. This is very bad idea. Kim is an editor of the
site and he / she has access to most of the areas in admin section.

So now, GNWP can share the newly created username and password with people
to whom GNWP wants to give access to dropbox files.

*Kim has to reset his password immediately*. So the old password will not
work and public can not login using already shared username and password
anymore.

Please let me know if you need more help on this matter.

On 10 August 2015 at 13:14, lauraroverts <notifications@github.com> wrote:

> Assigned #213 <https://github.com/akvo/akvo-sites/issues/213> to
> @rumeshkumar <https://github.com/rumeshkumar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/213#event-377705856>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542
