### ISSUE TITLE
issue key on server when attempt to connect FTP 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#214]
Message from @rumeshkumar , Kominski: 

Hi Laura,
I have done a small change to a file in gnwp to restrict access to admin area for a user and tried to deploy the change to server. But I could not find the files in the usual location. 

I also got message saying that the local key does not match with the key on the server when I tried to connect using FTP. 

If there is a new key, please send it to me. also please let me know where the Akvo site files currently. 
![akvo_ftp](https://cloud.githubusercontent.com/assets/4179989/9197242/00df9b02-4033-11e5-8fe2-c074ba4a1daa.jpg)

**Comment by rumeshkumar** [comment]
any update on this matter @osgl?

On 11 August 2015 at 17:44, lauraroverts <notifications@github.com> wrote:

> Message from @rumeshkumar <https://github.com/rumeshkumar> , Kominski:
>
> Hi Laura,
> I have done a small change to a file in gnwp to restrict access to admin
> area for a user and tried to deploy the change to server. But I could not
> find the files in the usual location.
>
> I also got message saying that the local key does not match with the key
> on the server when I tried to connect using FTP.
>
> If there is a new key, please send it to me. also please let me know where
> the Akvo site files currently.
> [image: akvo_ftp]
> <https://cloud.githubusercontent.com/assets/4179989/9197242/00df9b02-4033-11e5-8fe2-c074ba4a1daa.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/214>.
>



-- 
Regards,
N Rumeshkumar

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by osgl** [comment]
@rumeshkumar: not yet -- I'll take a look this week

**Comment by lauraroverts** [comment]
@osgl what is the status of this?

**Comment by lauraroverts** [comment]
@rumeshkumar @osgl Is this issue fixed?

**Comment by rumeshkumar** [comment]
@lauraroverts No, It is not fixed yet. If there is a new key, then I should
get it.

On 15 September 2015 at 14:38, lauraroverts <notifications@github.com>
wrote:

> @rumeshkumar <https://github.com/rumeshkumar> @osgl
> <https://github.com/osgl> Is this issue fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/214#issuecomment-140331003>.
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by osgl** [comment]
@orifito or @peeb: could you help with this issue for us please?

**Comment by Lynngre** [comment]
@rumeshkumar have you provided a public key to us at all?  https://help.github.com/articles/generating-ssh-keys/ @peeb will look into this asap

**Comment by peeb** [comment]
The error mentioned here is non-fatal. It would happen for example if one did

```
ssh sites.akvo.org
```
and then

```
ssh live10.live.akvo-ops.org
```
(the latter being the machine’s actual name.

Either way, clicking OK on the above warning dialog should dismiss it.

If you can't connect after clicking OK, then something else is the problem.

Please confirm, @rumeshkumar

**Comment by rumeshkumar** [comment]
@lunn

I am using the key which was used by the previous developer of Akvo sites.
I took over the projects after she left the company. So I did not provide
you a public key to you.

@peeb

I can connect after clicking "OK" and see the following list of directories.


Could you please let me know where are the Akvo site source files are
located?
​

-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin



Gapstars, 621, 2nd floor, Nawala Road, Rajagiriya, Sri Lanka.
W: www.gapstars.net | T: +94 114502542

**Comment by rumeshkumar** [comment]
I think the image is not attached. 
Please find it here

https://drive.google.com/file/d/0B5JebmR8_RXYcUhnRXFGMWsxUkk/view?usp=sharing

**Comment by Lynngre** [comment]
@rumeshkumar it's under /var (where it's always been).  I  do think you should get your own key/ssh access.

**Comment by rumeshkumar** [comment]
@lunn

but I do not see it in "/var/akvo/akvosites/code". Could you please let me
know the full path?

-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin



Gapstars, 621, 2nd floor, Nawala Road, Rajagiriya, Sri Lanka.
W: www.gapstars.net | T: +94 114502542

**Comment by Lynngre** [comment]
@rumeshkumar which server are you ssh-ing into?  It's DEF there USERNAME@THELIVESERVER:/var/akvo/akvosites$ when I ssh into the machine. Are you using terminal or how are you accessing the machine?

**Comment by Lynngre** [comment]
@rumeshkumar also note that we do allow FTP on our servers.

**Comment by rumeshkumar** [comment]
@lunn

I am using FTP (FlieZila) to connect to the server "sites.akvo.org". Please
click on the links below to see the settings I have done in my FTP.

https://drive.google.com/file/d/0B5JebmR8_RXYLVlTaW1kRDlQTjA/view?usp=sharing

https://drive.google.com/file/d/0B5JebmR8_RXYd19wemx4N2xIdHc/view?usp=sharing

-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin



Gapstars, 621, 2nd floor, Nawala Road, Rajagiriya, Sri Lanka.
W: www.gapstars.net | T: +94 114502542

**Comment by Lynngre** [comment]
@rumeshkumar I think that's the problem.  

Can you update the server to akvofoundation.org please?

**Comment by rumeshkumar** [comment]
@lunn

Okay, I have updated the server to akvofoundation and now, I can see the
files.

Thank you.


Best regards,
———
*N Rumeshkumar*
*Project Manager | **M*: +94 77 1304626 <+94771304626> | *@*:
rumesh@gapstars.net

*Gapstars*
621, 2nd Floor, Nawala Road, Rajagiriya, Sri Lanka | *T*: +94 11 4502542
<+94114502542> | *W*: http://www.gapstars.net
