### ISSUE TITLE
Add Food Security Portal (Akvopedia) as a page

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#215]
At http://www.rain4food.net a page need to be added in which the Food Security Portal (Akvopedia) will be visible. Same kind of page like http://www.rain4food.net/wiki/ but a different portal. 

RAIN Foundation will write some introduction text and should add a photo. 

Andreas Jonsson prepared an instruction on how to embed Akvopedia using the javascript gadget here:
http://akvopedia.org/resources/akvopedia-gadget/README

**Comment by Lynngre** [comment]
Andreas at Kreablo - Akvopedia, to check this.

**Comment by lauraroverts** [comment]
@Lynngre @AndreasJonsson any news on this?

**Comment by Lynngre** [comment]
@AndreasJonsson wrote a new widget/plugin for this & installed this for us on the Akvo Sites (ZZ theme) test server, so we can see how it works. I need to have a look at it in more detail.
We could add it to this installation some time this week?

**Comment by lauraroverts** [comment]
yes please, cause RAIN has been asking for this a couple of times now

**Comment by Lynngre** [comment]
I've added this as a draft but require the heading text/image.

**Comment by Lynngre** [comment]
Done http://www.rain4food.net/food-wiki/#akvopedia:Food%20&%20Nutrition%20Security%20Portal

**Comment by lauraroverts** [comment]
Thanks a lot. Looks good!
