### ISSUE TITLE
Remove support points

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-sites#218]
Hi Rumesh, 

Could you please remove the following support points in http://www.wandelenvoorwater.nl/wp-admin/admin.php?page=AWPR_supportpoint_detail ? 

It seems that I can't remove every support point, since the remove button doesn't appear behind every point, see screenshot.  
- RC Kommerijn (misspelled. RC Krommerijn needs to stay)
- RCs Bunnik Zeist 
- Rotary Club de Rottemeren & Simavi
- RC Wierden (appears two times at the list. one needs to be removed)

![screen shot 2015-12-14 at 16 59 35](https://cloud.githubusercontent.com/assets/4179989/11785959/643c1d0c-a284-11e5-9597-44d07336e30e.png)

thank you

**Comment by lauraroverts** [comment]
@rumeshkumar could you let me know if this can be done and how much time it would take approximately?

**Comment by rumeshkumar** [comment]
Hi Laura,

Sorry for the delay.

There are default support points which is added automatically and they can
not be deleted by admin currently. I am not sure whether there any any
records (schools) linked to those support points you have requested to
delete. What you want me to do if there are any support points liked to
already registered schools?

I will wok on this task on 4th of Jan 2016 and update you. It should be
small work.

On 28 December 2015 at 20:51, lauraroverts <notifications@github.com> wrote:

> @rumeshkumar <https://github.com/rumeshkumar> could you let me know if
> this can be done and how much time it would take approximately?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/218#issuecomment-167587181>.
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by rumeshkumar** [comment]
​I have removed the following support points

   - Rotary Club de Rottemeren & Simavi
   - RC Wierden (appears two times at the list. one needs to be removed)

​and I could not see any support points with the following name

- RC Kommerijn (misspelled. RC Krommerijn needs to stay)
- RCs Bunnik Zeist

On 29 December 2015 at 10:16, Rumeshkumar Navaratnam <rumesh@webgurus.lk>
wrote:

> Hi Laura,
>
> Sorry for the delay.
>
> There are default support points which is added automatically and they can
> not be deleted by admin currently. I am not sure whether there any any
> records (schools) linked to those support points you have requested to
> delete. What you want me to do if there are any support points liked to
> already registered schools?
>
> I will wok on this task on 4th of Jan 2016 and update you. It should be
> small work.
>
> On 28 December 2015 at 20:51, lauraroverts <notifications@github.com>
> wrote:
>
>> @rumeshkumar <https://github.com/rumeshkumar> could you let me know if
>> this can be done and how much time it would take approximately?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akvo/akvo-sites/issues/218#issuecomment-167587181>.
>>
>
>
>
> --
> Regards,
>
> *N Rumeshkumar*
>
> *Project Manager*
> M: +94 771304626 | Skype: rumeshin
>
> WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
> Sri Lanka.
> W: www.webgurus.lk | T: +94 114502542
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
Thanks. 
I can't fitnd RCs Bunnik Zeist either. But RC Kommerijn is there, see screenshot: 
![wandelen_voor_water_-_participant_registry__support_points_ _wandelen_voor_water_ _wordpress](https://cloud.githubusercontent.com/assets/4179989/12086549/8d55e090-b2cb-11e5-84b4-00b337e434d3.png)

**Comment by rumeshkumar** [comment]
okay, then there are going to be two RC Utrecht Krommerijn. is it?

On 4 January 2016 at 14:41, lauraroverts <notifications@github.com> wrote:

> Thanks.
> I can't fitnd RCs Bunnik Zeist either. But RC Kommerijn is there, see
> screenshot:
> [image: wandelen_voor_water_-_participant_registry__support_points_
> _wandelen_voor_water_ _wordpress]
> <https://cloud.githubusercontent.com/assets/4179989/12086549/8d55e090-b2cb-11e5-84b4-00b337e434d3.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/218#issuecomment-168617372>.
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
RC Utrecht Kommerijn needs to be removed. RC Utrecht KRommerijn (note the R) needs to stay.

**Comment by rumeshkumar** [comment]
done.

On 4 January 2016 at 15:15, lauraroverts <notifications@github.com> wrote:

> RC Utrecht Kommerijn needs to be removed. RC Utrecht KRommerijn (note the
> R) needs to stay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akvo/akvo-sites/issues/218#issuecomment-168625421>.
>



-- 
Regards,

*N Rumeshkumar*

*Project Manager*
M: +94 771304626 | Skype: rumeshin

WebGurus International Pvt. Ltd., 621, 2nd floor, Nawala Road, Rajagiriya,
Sri Lanka.
W: www.webgurus.lk | T: +94 114502542

**Comment by lauraroverts** [comment]
thank you
