### ISSUE TITLE
Hidden spam backlinks in site header

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-sites#220]
Walkingfowater.eu is making use of a theme called Quadro. Quadro includes an 'epanel' option under 'Appearance/Quadro theme options' select 'integration/code integration'.

The epanel option includes an area which allows you to easily add code to site outside of the site files for the individual multisite.

Akvofoundation.org multisite installation requires latest WordPress and plugin updates as well as password changes for all users asap.

![screen shot 2016-02-15 at 17 06 54](https://cloud.githubusercontent.com/assets/2675262/13070804/739a6a0a-d48f-11e5-8bf1-056fee1eb6f9.png)

**Comment by Lynngre** [comment]
@rumeshkumar I see you're using an account called 'Admin' for this multisite installation.  Quite a while ago Wordpress issued a notification re not using Admin as your username.  Could you please update your login or create a new super admin account for yourself?

**Comment by rumeshkumar** [comment]
I will check on this and update you by 23rd of this month.


Best regards,
———
*N Rumeshkumar*
*Project Manager | **M*: +94 77 1304626 <+94771304626> | *@*:
rumesh@gapstars.net

*Gapstars*
621, 2nd Floor, Nawala Road, Rajagiriya, Sri Lanka | *T*: +94 11 4502542
<+94114502542> | *W*: http://www.gapstars.net

**Comment by rumeshkumar** [comment]
I have changed the name "admin". So there are no more accounts with name
"admin".


Best regards,
———
*N Rumeshkumar*
*Project Manager | **M*: +94 77 1304626 <+94771304626> | *@*:
rumesh@gapstars.net

*Gapstars*
621, 2nd Floor, Nawala Road, Rajagiriya, Sri Lanka | *T*: +94 11 4502542
<+94114502542> | *W*: http://www.gapstars.net

**Comment by Lynngre** [comment]
Fixed & closed
